= Profile Page Project

:toc:
:toc-placement!:
:icons: font

== Introduction

This project is a profile page developed using React, MDBReact, and `react-slideshow-image`. +
It features a personal profile section, including a profile picture, contact buttons, social media links, and a slideshow displaying various technical skills. +

You can visit the project site on GitHub Pages: https://imanton2.github.io/about/ +

== GitHub Actions Workflow



== Installation

[source,bash]
----
# Clone the repository:
git clone https://github.com/IMAnton2/profile-page.git

# Navigate to the project directory:
cd profile-page

# Install dependencies:
npm install
----

== Usage

[source,bash]
----
# To start the development server, run:
npm start

# To create a production build, run:
npm run build
----

== Dependencies

* React
* MDBReact
* `react-slideshow-image`

== File Structure

* `src/App.js`: Main component file
* `src/anton2.svg`: Profile picture
* `src/Anton_Narodezki.pdf`: CV file
* `.github/workflows/node.js.yml`: workflow file, deploys to `gh-pages`

== Contact

For any inquiries or feedback, please contact:
* Anton Narodezki
* Email: imanton2@gmail.com

== License

This project is licensed under the MIT License.